# Generated by Django 4.1.6 on 2023-04-10 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taskapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='description')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Time add in time_create')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Time update in time_create')),
                ('completed', models.BooleanField(default=False)),
                ('username', models.ForeignKey(db_column='author', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='автор')),
            ],
            options={
                'verbose_name': 'Tasks',
            },
        ),
    ]
